rFactors([
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
},
{
    "id":"U_146_all_might",
    "skill":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/logo_skill_U.png",
    "cardImage":"https://raw.githubusercontent.com/mha-smashrising/rfactor-db/master/assets/U_146_all_might.jpg",
    "rarity":5,
    "character":"All Might",
    "attribute":"Purple",
    "rFactorScene":"SMASH HURRICANE",
    "STR":146,
    "HP":4348,
    "SP":0,
    "ATK":5208,
    "DEF":4742,
    "HIT":1173,
    "AVO":1055,
    "LUK":1473
}
])